### ISSUE TITLE
Highlight residues across views.

### ISSUE THREAD

**Issue by taylorr7** [sublime09/VisSIMP#13]

**Comment by MKOMohammed** [comment]
What do you mean?

**Comment by taylorr7** [comment]
We talked about this briefly yesterday (I think it was before you got there) but the idea was that if you click on a residue in one view, it would highlight that residue (with a light yellow or something) and then when you switch views, that residue would remain highlighted.

For example, if you click on residue 5 in the residue-order view, it would highlight that residue. And then, when you switched to the distance-order view, residue 5 would continue to be highlighted.

As an extension of this, it should be possible to "turn off" the highlight by clicking on a residue again, or some similar action.
