### ISSUE TITLE
Use the largest bin in the distance-order instead of the mean.

### ISSUE THREAD

**Issue by taylorr7** [sublime09/VisSIMP#20]

**Comment by MKOMohammed** [comment]
What do you mean by this issue?

**Comment by taylorr7** [comment]
Currently, the distance order view places the residue number where the mean of that residue probability is. We talked briefly about changing this so instead of using the mean, we would instead place the residue number wherever the largest bin was instead.

For example, if residue 5 had a mean of 2.4 but the highest probability (largest bin) was at 2.1, we should put a "5" at 2.1, instead of 2.4 like it is now.
