### ISSUE TITLE
Axis labeling

### ISSUE THREAD

**Issue by sublime09** [sublime09/VisSIMP#5]
Add axis labels.  
All visualizations will have x as residue, y as distance (float).  
Gridlines may be helpful.  

Labels will need changes though based on ordering:
Residue order vis will have x ordered by residue number (i.e. 1, 2, 3, ..., 41, 42)
Heatmap view will have same order as Residue order view.  
Distance order vis will have x sorted and ordered by minimum distance (i.e. 5, 27, 14, ... , 2, 11, 40 when 5 is very close and 40 is very far)  

Start with the heatMap vis.  We will keep this open until the other views / vis are in and then.

**Comment by MKOMohammed** [comment]
Done
